services:
  # ============ Catalog ============
  #Catalog.Api
  catalog.api:
    image: catalog.api
    platform: linux/amd64
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
    container_name: catalog-api
    ports:
      - "9000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017
      - DatabaseSettings__DatabaseName=CatalogDb
      - DatabaseSettings__ProductsCollection=Products
      - DatabaseSettings__BrandsCollection=Brands
      - DatabaseSettings__TypesCollection=Types
    depends_on:
      - catalogdb

 #CatalogDb-MongoDb
  catalogdb:
    image: mongo
    container_name: catalogdb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # ============ Basket ============
  
  #Redis_-BasketDb
  redis:
    image: redis
    container_name: basketdb
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

 #Basket.Api
  basket.api:
    image: basket.api
    platform: linux/amd64
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile
    container_name: basket-api
    ports:
      - "9001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - RedisSettings__ConnectionString=redis:6379
    depends_on:
      - redis

volumes:
  mongo_data:
  redis_data: